package db;
// Generated 17.12.2017 7:19:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Short id;
     private String author;
     private String commenttext;
     private Date commentdate;

    public Comments() {
    }

	
    public Comments(Date commentdate) {
        this.commentdate = commentdate;
    }
    public Comments(String author, String commenttext, Date commentdate) {
       this.author = author;
       this.commenttext = commenttext;
       this.commentdate = commentdate;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getCommenttext() {
        return this.commenttext;
    }
    
    public void setCommenttext(String commenttext) {
        this.commenttext = commenttext;
    }
    public Date getCommentdate() {
        return this.commentdate;
    }
    
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }




}


