package db;
// Generated 17.12.2017 7:19:17 by Hibernate Tools 4.3.1



/**
 * Purchases generated by hbm2java
 */
public class Purchases  implements java.io.Serializable {


     private Integer id;
     private Integer orderId;
     private Integer price;
     private Integer modelId;

    public Purchases() {
    }

    public Purchases(Integer orderId, Integer price, Integer modelId) {
       this.orderId = orderId;
       this.price = price;
       this.modelId = modelId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getModelId() {
        return this.modelId;
    }
    
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }




}


